# Usando a imagem moderna padrão
FROM node:18-slim

WORKDIR /usr/src/app

# Nenhuma instalação manual de 'libssl' é necessária aqui

COPY package*.json ./
RUN npm install

COPY prisma ./prisma/

COPY certs/nicolasec-WIN.cer /usr/local/share/ca-certificates/nicolasec-WIN.crt

RUN npx prisma generate

COPY . .

EXPOSE 8080

CMD [ "npm", "run", "start" ]